###*
# Created by andrey on 13.02.17.
###
### слайдер ###
$ ->
  $('#slides').superslides
    inherit_width_from: '.wide-container'
    inherit_height_from: '.wide-container'
  return
### menu resize ###
$(document).on 'scroll', ->
  if $(document).scrollTop() > 600
    $('header').addClass 'smaller'
  else
    $('header').removeClass 'smaller'
  return
### hamburger ###
$('.hamburger').on 'click', ->
  if $(this).hasClass('is-active')
    $(this).removeClass 'is-active'
    $('.main_menu').removeClass 'active'
  else
    $(this).addClass 'is-active'
    $('.main_menu').addClass 'active'
  return
### ajax request for first 6 photos ###
get_first_photos = (id) ->
  $.ajax(
    type: 'GET'
    url: 'get_first_photos'
    data: id: id).done (response) ->
      $('#first_photos').html response
      overlay_width_calc()
      return
  return
### photo overlay width calculating ###
overlay_width_calc = ->
  $('.photo').each ->
    width = $(this).find('img').width()
    image = $(this).find('.image-wrap')
    hover = $(this).find('.hover-wrap')
    image.width width
    hover.width width
    return
  return
### email validation ###
isEmail = (email) ->
  regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/
  regex.test email
### set full photoalbum link ###
$(document).ready ->
  overlay_width_calc()
  get_first_photos 0
  _href = $('.get_first_photos').first().attr('href')
  $('#show_full_album').attr 'href', _href
  return
$(window).resize ->
  overlay_width_calc()
  return
### photoalbum link click ###
$(document).on 'click', '.get_first_photos', (event) ->
  event.preventDefault()
  _id = $(this).data('id')
  _href = $(this).attr('href')
  get_first_photos _id
  $('#show_full_album').attr 'href', _href
  return
### mail send function ###
$('.contacts_form').on 'submit', (event) ->
  event.preventDefault()
  if isEmail($(this).find('input[name=email]').val())
    formData = $(this).serialize()
    formMethod = $(this).attr('method')
    formUrl = $(this).attr('action')
    fio = $(this).find('input[name=fio]')
    email = $(this).find('input[name=email]')
    mess = $(this).find('textarea[name=message]')
    $.ajax(
      type: formMethod
      url: formUrl
      data: formData).done (response) ->
        fio.val ''
        email.val ''
        mess.val ''
        message.show response['message'], response['status']
        return
  else
    message.show $('.message-container').data('email-error'), 'error'
  return
### language setter toggler ###
$('.languageSet .toggler').on 'click', (e) ->
  e.preventDefault()
  langMenu = $('.languageSet')
  if !langMenu.hasClass('opened')
    langMenu.css 'right', '-68px'
    langMenu.addClass 'opened'
    $(this).find('img.opened').show()
    $(this).find('img.closed').hide()
  else
    langMenu.css 'right', '-200px'
    langMenu.removeClass 'opened'
    $(this).find('img.opened').hide()
    $(this).find('img.closed').show()
  return

# ---
# generated by js2coffee 2.2.0